# Generated by Django 2.1.2 on 2018-10-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miyagi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=55)),
                ('city_name_ja', models.CharField(max_length=55)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('predicted_data', models.FileField(upload_to='data/')),
            ],
        ),
    ]
