# Generated by Django 2.1.2 on 2018-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20181019_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichi',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='aichi',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='akita',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='akita',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='aomori',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='aomori',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='chiba',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='chiba',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='ehime',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='ehime',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='fukui',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='fukui',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='fukuoka',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='fukuoka',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='fukushima',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='fukushima',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='gifu',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='gifu',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='gunma',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='gunma',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='hiroshima',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='hiroshima',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='hokkaido',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='hokkaido',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='hyogo',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='hyogo',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='ibaraki',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='ibaraki',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='ishikawa',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='ishikawa',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='iwate',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='iwate',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kagawa',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kagawa',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kagoshima',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kagoshima',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kanagawa',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kanagawa',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kochi',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kochi',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kumamoto',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kumamoto',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kyoto',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='kyoto',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='mie',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='mie',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='miyagi',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='miyagi',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='miyazaki',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='miyazaki',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='nagano',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='nagano',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='nagasaki',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='nagasaki',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='nara',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='nara',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='niigata',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='niigata',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='oita',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='oita',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='okayama',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='okayama',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='okinawa',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='okinawa',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='osaka',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='osaka',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='saga',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='saga',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='saitama',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='saitama',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='shiga',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='shiga',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='shimane',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='shimane',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='shizuoka',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='shizuoka',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='tochigi',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='tochigi',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='tokushima',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='tokushima',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='tokyo',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='tokyo',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='tottori',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='tottori',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='toyama',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='toyama',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='wakayama',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='wakayama',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='yamagata',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='yamagata',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='yamaguchi',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='yamaguchi',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='yamanashi',
            name='wind_data',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='yamanashi',
            name='wind_tendency',
            field=models.FileField(null=True, upload_to='data/'),
        ),
    ]
